language: node_js
node_js:
  - 13

branches:
  only:
    - master

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed .
  - docker tag udagram-api-feed brestolho/udagram-api-feed:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker push brestolho/udagram-api-feed
